version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 5

  python:
    build: .
    depends_on:
      selenium:
        condition: service_healthy
    command: python /app/script.py
    volumes:
      - ./script.py:/app/script.py
